services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
      - ./storage:/rails/storage
    environment:
      - RAILS_ENV=development
    command: bin/rails server -b 0.0.0.0
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data

volumes:
  redis_data: