workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Petstore API:
        inputs:
            - location: ./webhooks-ts.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/speakeasy-self/speakeasy-self/petstore-api
targets:
    petstore:
        target: typescript
        source: Petstore API
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/speakeasy-self/speakeasy-self/petstore-api-typescript-code-samples
            blocking: false
