workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Coffee Orders API:
        inputs:
            - location: ../openapi.json
        registry:
            location: registry.speakeasyapi.dev/ritza-rzx/ritza/coffee-orders-api
targets:
    coffee-example-api-sdk:
        target: typescript
        source: Coffee Orders API
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/ritza-rzx/ritza/coffee-orders-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
        testing:
            enabled: true
