workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Todo API:
        inputs:
            - location: ./openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/speakeasy-self/speakeasy-self/todo-api
targets:
    gtd:
        target: python
        source: Todo API
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/speakeasy-self/speakeasy-self/todo-api-python-code-samples
            labelOverride:
                fixedValue: Python (SDK)
            blocking: false
