workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    openapi:
        inputs:
            - location: openapi.yaml
        overlays:
            - location: overlay.yaml
        output: combined-spec.yaml
        registry:
            location: registry.speakeasyapi.dev/ash-testing/ash-testing/openapi
targets:
    overlay-example:
        target: typescript
        source: openapi
