openapi: 3.0.0
info:
  title: Store Demo API
  version: "1.0.0"
paths:
  /products:
    post:
      summary: Create a new product
      operationId: createProduct
      requestBody:
        description: The product details to create.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The name of the product.
                description:
                  type: string
                  description: A brief description of the product.
              required:
                - name
      responses:
        "201":
          description: Product created successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  productId:
                    type: string
                    description: Unique identifier for the product.
                  name:
                    type: string
                  description:
                    type: string
        "400":
          description: Invalid input provided.
  /products/{productId}/pricing:
    post:
      summary: Add pricing to a product
      operationId: addPricing
      parameters:
        - name: productId
          # x-speakeasy-name-override: id
          in: path
          description: ID of the product to add pricing to.
          required: true
          schema:
            type: string
      requestBody:
        description: Pricing details for the product.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                  description: Price amount in smallest currency unit (e.g., cents).
                currency:
                  type: string
                  description: Currency code (e.g., USD).
              required:
                - amount
                - currency
      responses:
        "200":
          description: Pricing added successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  productId:
                    # x-speakeasy-name-override: id
                    type: string
                  pricing:
                    type: object
                    properties:
                      amount:
                        type: number
                      currency:
                        type: string
        "400":
          description: Invalid pricing details provided.
  /products/{productId}/publish:
    post:
      summary: Publish a product
      operationId: publishProduct
      parameters:
        - name: productId
          # x-speakeasy-name-override: id
          in: path
          description: ID of the product to publish.
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Product published successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  productId:
                    # x-speakeasy-name-override: id
                    type: string
                  status:
                    type: string
                    description: Publication status of the product.
        "404":
          description: Product not found.
